Repository Peripli/service-broker-proxy-cf, pull requests merged in 2019-06, with the labels that each got.

#62 Adapt to SM not sending last_known_revision when no notifications are present
  Gopkg.lock
  Gopkg.toml
Labels: breaking-change, request-review

#63 Fix unlimited go routines
  Gopkg.lock
  application.yml
  cf/cf_suite_test.go
  cf/client.go
  cf/client_test.go
  cf/config.go
  cf/config_test.go
  cf/fetch_catalog_test.go
  cf/service_access.go
  cf/service_broker.go
  cf/service_broker_test.go
  cf/service_visibilities.go
  cf/service_visibilities_test.go
  main.go
  manifest.yml
Labels: request-review

#65 Use SM credentials to register proxy broker
  Gopkg.lock
  cf/client.go
  cf/client_test.go
  cf/config_test.go
  cf/fetch_catalog_test.go
  cf/service_broker.go
  cf/service_broker_test.go
  cf/service_visibilities.go
Labels: release
